/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculators;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sayn
 */
public class Calculator_R_Button extends javax.swing.JFrame {

    String operation,answer;
    double firstnum,secondnum,result;
    
    /**
     * Creates new form Calculator_R_Button
     */
    public Calculator_R_Button() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        back = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        six = new javax.swing.JButton();
        two = new javax.swing.JButton();
        per = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        one = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        div = new javax.swing.JButton();
        three = new javax.swing.JButton();
        add = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        ops = new javax.swing.JButton();
        equal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        display.setText(" ");
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 46));

        clear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clear.setText("C");
        clear.setPreferredSize(new java.awt.Dimension(60, 60));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        four.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        four.setText("4");
        four.setPreferredSize(new java.awt.Dimension(60, 60));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel1.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        five.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        five.setText("5");
        five.setPreferredSize(new java.awt.Dimension(60, 60));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel1.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        back.setText("CE");
        back.setPreferredSize(new java.awt.Dimension(60, 60));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        seven.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        seven.setText("7");
        seven.setPreferredSize(new java.awt.Dimension(60, 60));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel1.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        eight.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        eight.setText("8");
        eight.setPreferredSize(new java.awt.Dimension(60, 60));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel1.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        six.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        six.setText("6");
        six.setPreferredSize(new java.awt.Dimension(60, 60));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel1.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        two.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        two.setText("2");
        two.setPreferredSize(new java.awt.Dimension(60, 60));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel1.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        per.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        per.setText("%");
        per.setPreferredSize(new java.awt.Dimension(60, 60));
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        jPanel1.add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        nine.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nine.setText("9");
        nine.setPreferredSize(new java.awt.Dimension(60, 60));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel1.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        one.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        one.setText("1");
        one.setPreferredSize(new java.awt.Dimension(60, 60));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel1.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        mul.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        mul.setText("*");
        mul.setPreferredSize(new java.awt.Dimension(60, 60));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        jPanel1.add(mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        zero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        zero.setText("0");
        zero.setPreferredSize(new java.awt.Dimension(60, 60));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel1.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        div.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        div.setText("/");
        div.setPreferredSize(new java.awt.Dimension(60, 60));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        three.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        three.setText("3");
        three.setPreferredSize(new java.awt.Dimension(60, 60));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel1.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        add.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        add.setText("+");
        add.setPreferredSize(new java.awt.Dimension(60, 60));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        minus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        minus.setText("-");
        minus.setPreferredSize(new java.awt.Dimension(60, 60));
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        jPanel1.add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        decimal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        decimal.setText(".");
        decimal.setPreferredSize(new java.awt.Dimension(60, 60));
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });
        jPanel1.add(decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        ops.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ops.setText("±");
        ops.setPreferredSize(new java.awt.Dimension(60, 60));
        ops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsActionPerformed(evt);
            }
        });
        jPanel1.add(ops, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        equal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        equal.setText("=");
        equal.setPreferredSize(new java.awt.Dimension(60, 60));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

       String back = null;
       if(display.getText().length() > 0 )
       {
           StringBuilder s=new StringBuilder(display.getText());
           s.deleteCharAt(display.getText().length() - 1);
           back = s.toString();
           display.setText(back);
       }
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       
             display.setText(null);
    }//GEN-LAST:event_backActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
       String x = display.getText() + zero.getText();
       display.setText(x);
    }//GEN-LAST:event_zeroActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
       String x = display.getText() + one.getText();
       display.setText(x);
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
       String x = display.getText() + two.getText();
       display.setText(x);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        String x = display.getText() + three.getText();
       display.setText(x);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        String x = display.getText() + four.getText();
       display.setText(x);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        String x = display.getText() + five.getText();
       display.setText(x);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        String x = display.getText() + six.getText();
       display.setText(x);
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        String x = display.getText() + seven.getText();
       display.setText(x);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
       String x = display.getText() + eight.getText();
       display.setText(x);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        String x = display.getText() + nine.getText();
       display.setText(x);
    }//GEN-LAST:event_nineActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "%";
    }//GEN-LAST:event_perActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "+";
    }//GEN-LAST:event_addActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
       firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "-";
    }//GEN-LAST:event_minusActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
       firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "*";
    }//GEN-LAST:event_mulActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "/";
    }//GEN-LAST:event_divActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
       if(! display.getText().contains("."));
       {
           display.setText(display.getText() + decimal.getText());
       }
    }//GEN-LAST:event_decimalActionPerformed

    private void opsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsActionPerformed
        double ops = Double.parseDouble(String.valueOf(display.getText()));
        ops = ops * (-1);
        display.setText(String.valueOf(ops));
    }//GEN-LAST:event_opsActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        secondnum = Double.parseDouble(display.getText());
        
        if(operation == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            display.setText(answer);
        }
        else if(operation == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            display.setText(answer);
        }
        else if(operation == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            display.setText(answer);
        }
        else if(operation == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            display.setText(answer);
        }
        else if(operation == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            display.setText(answer);
        }
    }//GEN-LAST:event_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Calculator_R_Button().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Calculator_R_Button.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Calculator_R_Button.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Calculator_R_Button.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Calculator_R_Button.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton decimal;
    private javax.swing.JTextField display;
    private javax.swing.JButton div;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minus;
    private javax.swing.JButton mul;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton ops;
    private javax.swing.JButton per;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
